### ISSUE TITLE
Unable to lookup history because parsing fails (on Linux)

### ISSUE THREAD

**Issue by aawc** [autochthe/history#1]
On my machine, the `bash_all_history` file is being written as expected.
However, when I try to lookup history with `h`, it fails to parse the lines in `bash_all_history` file correctly and returns an empty screen.

On debugging, I found that this happens because of the extra `'\x00'` that's appended at the end of the line. If I remove it, the parsing works as expected.

I'm sure there's a good reason for having it, but I can't figure it out.

It might be useful to add a comment for why it is needed (and make the parsing work with it) or remove the `'\x00'` altogether. I have a patch for removing it that I'll associate with this issue shortly.

**Comment by aawc** [comment]
#https://github.com/aawc/history/commit/814d1b568307731aff671b6f9354fc5c8b77164d

**Comment by aawc** [comment]
#2

**Comment by astralarya** [comment]
The `\x00` outputs a null character into the output.  This is required to allow handling of commands containing newlines, for example:

```
echo 'foo
ababa'
```

Interesting that parsing fails on your machine.  This script was originally written for/on Ubuntu Linux.  Could you tell me what version of gawk you are using?  Also could you tell me what specific parsing error you get?

**Comment by astralarya** [comment]
@aawc Can you provide more details about this issue?
