### ISSUE TITLE
select history causes crash

### ISSUE THREAD

**Issue by CeleritasCelery** [autochthe/history#4]
First off, I love your plugin. However when I try to run the `h!` command to select from history it causes my shell to crash immediately. I went into the source and changed the function name from `h!` to `hs` and it works fine. when I try `type h!` it shows the correct function. Any idea why this might be or how I could debug it?

**Comment by astralarya** [comment]
What is your shell version and operating system?

**Comment by CeleritasCelery** [comment]
Bash version: 4.3.0
OS: SUSE Linux Enterprise Server 11 SP4

also I have uncovered that running `h!` with an argument such as a search term will cause it to work just fine. But running it without a search term causes the crash.

**Comment by astralarya** [comment]
Hmm interesting.  Do you get any output when it crashes?  If you don't have any output, try the following:

    bash -x
    source ~/.bashrc        (or .bash_profile)
    h!

**Comment by astralarya** [comment]
Alternatively here is a better way:

    set -x
    h!
    set +x

**Comment by CeleritasCelery** [comment]
I don't get any output before it crashes. Even with `set -x`. However I did some more digging and it only happens when I am in `tmux`. If I run a shell normal is gives me no problems. So it may be their problem but I can't be sure.

**Comment by astralarya** [comment]
Interesting.  It does sound like potentially a tmux problem.  When you say it doesn't give any output, what happens?  Does your entire terminal session end?  Or do you just get no output and return to the prompt?

**Comment by CeleritasCelery** [comment]
It closes the pane immediately, as soon as I hit enter. I assumed that it was crashing but it could also be a call to exit.

**Comment by astralarya** [comment]
Ok, so looking at the tmux manual (http://man.openbsd.org/OpenBSD-current/man1/tmux.1), it appears that `!` is a keybinding that breaks the current pane out of the window.  However, this should only happen after the attention sequence (default `Ctrl+B`).  Also the section on **Commands**  has several uses of `!` that may or may not be relevant (sorry, I'm not very familiar with tmux).

What happens when you try `h!<SPACE>`?

**Comment by astralarya** [comment]
It may also be helpful to see the output of the following command:  `tmux list-keys`

**Comment by CeleritasCelery** [comment]
adding a space after `h!` works. Curious. I don't think it is keybinding problem because any tmux command I have involving `!` (`break-pane` is the only one) require the prefix.

**Comment by astralarya** [comment]
What happens if you remove `source history.sh` from your bashrc? Does the tmux still close with `h!`?

**Comment by CeleritasCelery** [comment]
Yes it still closes it. Interesting. This seems to not be an issue with your plugin itself but perhaps some command conflict with tmux. Thanks for helping me rule that out.

**Comment by astralarya** [comment]
Does it work to `alias hs=h!`?

**Comment by CeleritasCelery** [comment]
Yes that works fine
