### ISSUE TITLE
shared history

### ISSUE THREAD

**Issue by gigaguy** [autochthe/history#5]
My home dir is share across all my servers.  So they can all see .bash_all_history and all load the same .bash_profile.  But only only server actually records the history, and even then it seems like its only partially recording.  I've also tried loading in .bashrc.  These are all centos6 servers.

It also doesnt seem to be logging everything.

**Comment by astralarya** [comment]
Interesting. Could you provide some more details?  I personally use this script in a cluster computing environment that shares my home directory across nodes (also using CentOS).

It would be helpful if you could explain step by step what reproduces the problem.

**Comment by gigaguy** [comment]
Happens on both ubuntu & centos6
Since all server share the .bash_profile they should all be sourcing the hist config. Also, they are all writing to the same file.  I just typed "h" on a server i've been on all day and get this.
`user@server     /nfs/blah/admin/git    2017-03-09 21:21:41     sudo reboot`
Obviously there has been history since 3/9.  ldh, dh, h, all give the same output.  Which appears to be random.  Some saved some not.  .bash_history still appears to be saving as well, which proved there is more history 'h' is not showing.

What more info do you need?  I can try removing everything im sourcing in the profile and see if that helps.

**Comment by astralarya** [comment]
What do you get with `echo $ALL_HISTORY_FILE`?  Then what is the output of `cat $ALL_HISTORY_FILE`?

**Comment by gigaguy** [comment]
echo $ALL_HISTORY_FILE
`/homepath/.bash_all_history`

cat $ALL_HISTORY_FILE - give me history, but its sparse.

So I removed everything from my profile and loaded only history.  i noticed i was loading other hist settings.  

So far after commenting/removing the following settings, it appears to be working correctly. Any idea which the issue could be?  I understand the what the ignore does and those arent the missing commands.

`
#shopt -s histappend
#Combine multiline commands into one in history
#shopt -s cmdhist
#export HISTCONTROL=erasedups:ignorespace
#export HISTIGNORE="&:ll:ls:[bf]g:exit:cd:la:l:pwd:df:clear:cls"
`

**Comment by astralarya** [comment]
You are overriding `history.sh`'s setting `export HISTCONTROL='ignorespace'`.  See what happens if you remove the line referencing `HISTCONTROL`.

**Comment by gigaguy** [comment]
Well, it seems to be working now.  it wasnt the HISTCONTROL, so it must've been one of the other lines.  But im too lazy to figure out which.  Dont want to break it again, its too awesome :+1: 

Thanks for your help !
